namespace crm_ai.Models
{
    /// <summary>
    /// The strategy layer — generated by AI from SegmentProfile.
    /// This sits between audience analysis and content generation.
    /// Having an explicit strategy object makes the system explainable
    /// and gives the jury something concrete to discuss.
    /// </summary>
    public class CampaignStrategy
    {
        public int Id { get; set; }
        public int CampaignId { get; set; }
        public Campaign Campaign { get; set; } = null!;

        // Core strategy decisions
        public string CampaignType { get; set; } = "";
        // "reactivation" | "retention" | "conversion" | "welcome" | "winback" | "upsell"

        public string Tone { get; set; } = "";
        // "urgent" | "friendly" | "premium" | "promotional" | "informational"

        public string RecommendedTemplateId { get; set; } = "";
        // ID from templates.json — matched deterministically to CampaignType + Tone

        public string? RecommendedSendTime { get; set; }
        // e.g. "Thursday 12:00" — from visit pattern analysis

        // Explainability — WHY this strategy was chosen
        // This is the key differentiator: the system explains its reasoning
        public string ExplanationJson { get; set; } = "[]";
        // Serialised List<StrategyExplanationPoint>

        public DateTime GeneratedAt { get; set; } = DateTime.UtcNow;
    }

    /// <summary>
    /// One reason in the strategy explanation.
    /// Rendered on the frontend as bullet points under "Why this strategy?"
    /// </summary>
    public class StrategyExplanationPoint
    {
        public string Signal { get; set; } = "";
        // The data fact: "67% of this audience has been inactive for 3+ months"

        public string Implication { get; set; } = "";
        // The reasoning: "Lapsed customers respond better to urgency than promotion"

        public string Decision { get; set; } = "";
        // The choice made: "Tone set to urgent, template type set to winback"
    }
}