using crm_ai.DTOs;

namespace crm_ai.Services.Interfaces
{
    public interface IAiService
    {
        /// <summary>
        /// Takes a structured selection group and returns a plain-English
        /// marketing description generated by Groq AI.
        /// </summary>
        Task<AiDescriptionResponseDto> GenerateSelectionDescriptionAsync(
            SelectionGroupDto rootGroup);

        /// <summary>
        /// Takes a plain-English audience description and returns a fully
        /// built rule tree with real TreeNode IDs.
        /// Uses Few-Shot prompting + Confidence scoring.
        /// </summary>
        Task<AiSelectionResponseDto> GenerateSelectionFromPromptAsync(
            string prompt,
            string? name = null);

        /// <summary>
        /// Takes a manually built rule tree and validates it for logical issues.
        /// Returns a plain-English summary + list of warnings/errors.
        /// </summary>
        Task<AiValidationResponseDto> ValidateSelectionAsync(
            SelectionGroupDto rootGroup);

        /// <summary>
        /// Conversational flow — handles multi-turn dialogue.
        /// Decides whether to ask clarifying questions, build, or refine rules.
        /// Frontend sends full history every turn (stateless backend).
        /// </summary>
        Task<ConversationResponseDto> ContinueConversationAsync(
            ConversationRequestDto request);
        Task<IntentCheckResponseDto> CheckIntentAsync(IntentCheckRequestDto request);

        Task<AiDescriptionResponseDto> GenerateDescriptionOnDemandAsync(SelectionGroupDto rootGroup);
        Task<string> GenerateNameOnDemandAsync(string description);
        Task<(int Score, int Tokens)> ScoreConfidenceOnDemandAsync(string intent, SelectionGroupDto rootGroup);
        Task<(string Response, int TokensUsed)> CallPublicAsync(
            string systemPrompt, string userPrompt, int maxTokens = 200);
    }
}